<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DotFuzz/DotFuzz.csproj" />
  </ItemGroup>
</Project>
